development:
  cloud_name: <%= Rails.application.credentials[:cloud][:cloud_name] %>
  api_key: <%= Rails.application.credentials[:cloud][:api_key] %>
  api_secret: <%= Rails.application.credentials[:cloud][:api_secret] %>
  enhance_image_tag: true
  static_file_support: false
